import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://engine.surfconext.nl/authentication/idp/single-sign-on/key:20230503?SAMLRequest=fVLBjtowEP2VyPckxiFssQgrumhVpK1KIdtDb15nCFaTcZpxKPv3NSGwtAculjXzZt6beTN7PNZVcICWjMWMjSLOAkBtC4Nlxl7z5%2FATe5zPSNWVaOSic3vcwO8OyAW%2BEEmeMxnrWpRWkSGJqgaSTsvt4uuLFBGXTWud1bZiwYIIWuepnixSV0O7hfZgNLxuXjK2d64hGcfaIoJ2EXXtzv%2Fh6CKs4sqWBuOeLiaysTWFxpIFS6%2FFoHK9%2FksLQA%2BG%2Fzoorx7QGd2DY1M0MfkxKwjJlBj60C94l4KLhKc8YcGzbTX0I2dspyoCFqyWGVtsvidvoMV4EooiScKx8M9UjESY8LHmD3yqd%2FDgsbRWROYAH9VEHayQnEKXMU80CXkScpGPuExSOUqjaZr%2BZMF62Ndng2cf7i337Qwi%2BSXP1%2BH62zZnwY%2BLnx7ABvdkz97e2na%2Fsbp4xeZ3nZnFt%2F2vt7LVtvG6TsMc359sdxp5xK7p4YqgXS3nqhITDfs%2FZaS0PiEpslhArbCItK0Hgn9rrsGB5yNwe6Tzvw%3D%3D&RelayState=f3a9edc9-8052-4411-939d-08470847a9d1&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=TzRjTZBCsRCLQTwVXuGb01uJ%2FgPW9LIFQOoj%2BgHAAVvUY0dpUP2pz4OMmDuPnQQauGo4R09EwIUUItyfr4sqaGsRS1zMrvn5W0ScbvdjLnEIetyiSOlZPwF%2Bwy1LdSUjFo8ns0RUSX3UGvm64qlKxdCOHAMO8pP25JnJmYm3cMhCuc4RUsA%2Bu61g8JvUWdMSf%2Fsw8JC069wwY7wijLTItMGSiDdLUq79o2Oqd7v24R5OWxTHZ40ktebc6VYSUNh1ILJBf7YfTSZqg5hxQ0%2BkM0962FLB4YQm8yQvYB5ZlTHZnJxNnaLjmaB7osBcEp0QjkDxUHrTt8xTCwi4w%2By98A%3D%3D")
    page.get_by_role("heading", name="Login with University of").click()
    page.locator("#branding").click()
    page.get_by_role("textbox", name="User Account").click()
    page.get_by_role("textbox", name="User Account").fill("fschrec1@uva.nl")
    page.get_by_role("textbox", name="User Account").press("Tab")
    page.get_by_role("textbox", name="Password").fill("UvABeta1231!")
    page.get_by_role("textbox", name="Password").press("Enter")
    page.goto("https://s1-eu.ariba.com/Buyer/Main/aw?awh=r&awssk=JVpc8cQoM6LouM3y&realm=uva-1&dard=1")
    page.get_by_role("button", name="OK").click()
    page.get_by_role("button", name="Go back to the previous page").click()
    page.get_by_role("button", name="close").click()
    page.get_by_role("link", name="Request a non-catalog item", exact=True).click()
    page.get_by_role("textbox", name="Product name Required").click()
    page.get_by_role("textbox", name="Product name Required").fill("test")
    page.get_by_role("button", name="Shopping Cart3 items in the").click()
    page.get_by_role("button", name="Go to checkout").click()
    page.get_by_role("button", name="Go back to the previous page").click()
    page.get_by_role("button", name="Shopping Cart3 items in the").click()
    page.get_by_role("button", name="Delete SM2L03").get_by_label("Delete").click()
    page.get_by_role("button", name="Delete SM2L03").get_by_label("Delete").click()
    page.get_by_role("textbox", name="Product name Required").fill("test")
    page.get_by_role("combobox", name="Category Required").click()
    page.get_by_role("link", name="900006 (Laboratory – Items").click()
    page.get_by_role("textbox", name="Description Required").click()
    page.get_by_role("textbox", name="Description Required").fill("test")
    page.get_by_role("textbox", name="Quantity Required").click()
    page.get_by_role("textbox", name="Quantity Required").fill("1")
    page.get_by_role("textbox", name="Unit price Required").click()
    page.get_by_role("textbox", name="Unit price Required").fill("1")
    page.get_by_role("button", name="View all suppliers").click()
    page.get_by_role("searchbox", name="Search").click()
    page.get_by_role("searchbox", name="Search").fill("thorlabs")
    page.get_by_role("searchbox", name="Search").press("Enter")
    page.get_by_text("Thorlabs GmbH").click()
    page.get_by_role("button", name="Select, emphasized").click()
    page.get_by_role("button", name="Add to cart").click()
    page.get_by_role("button", name="Added 1 test to cart, Close").click()
    page.get_by_title("more actions").click()
    page.get_by_role("button", name="Create new").click()
    page.get_by_role("textbox", name="Product name Required").click()
    page.get_by_role("textbox", name="Product name Required").fill("test2")
    page.get_by_role("textbox", name="Description Required").click()
    page.get_by_role("textbox", name="Description Required").fill("test2d")
    page.get_by_role("combobox", name="Category Required").click()
    page.get_by_role("link", name="900006 (Laboratory – Items").click()
    page.get_by_role("textbox", name="Quantity Required").click()
    page.get_by_role("textbox", name="Quantity Required").fill("2")
    page.get_by_role("textbox", name="Unit price Required").click()
    page.get_by_role("textbox", name="Unit price Required").fill("2")
    page.get_by_role("button", name="View all suppliers").click()
    page.get_by_role("searchbox", name="Search").click()
    page.get_by_role("searchbox", name="Search").fill("thorlabs")
    page.get_by_role("searchbox", name="Search").press("Enter")
    page.get_by_text("Thorlabs GmbH").click()
    page.get_by_role("button", name="Select, emphasized").click()
    page.get_by_role("button", name="Add to cart").click()
    page.get_by_role("button", name="Added 2 test2 to cart, Close").click()
    page.get_by_title("more actions").click()
    page.get_by_role("button", name="Create new").click()
    page.get_by_role("textbox", name="Product name Required").click()
    page.get_by_role("textbox", name="Product name Required").fill("test3")
    page.get_by_role("textbox", name="Description Required").click()
    page.get_by_role("textbox", name="Description Required").fill("test3d")
    page.get_by_role("combobox", name="Category Required").click()
    page.get_by_role("link", name="900006 (Laboratory – Items").click()
    page.get_by_role("textbox", name="Quantity Required").click()
    page.get_by_role("textbox", name="Quantity Required").fill("3")
    page.get_by_role("textbox", name="Unit price Required").click()
    page.get_by_role("textbox", name="Unit price Required").fill("3")
    page.get_by_role("button", name="View all suppliers").click()
    page.get_by_role("searchbox", name="Search").click()
    page.get_by_role("searchbox", name="Search").fill("thorlabs")
    page.get_by_role("searchbox", name="Search").press("Enter")
    page.get_by_text("Thorlabs GmbH").click()
    page.get_by_role("button", name="Select, emphasized").click()
    page.get_by_role("button", name="Add to cart").click()
    page.get_by_role("button", name="Go to checkout").click()
    page.locator("#NeedBy").get_by_role("combobox", name="Need-by Date Need By Date").click()
    page.get_by_role("button", name="20").click()
    page.get_by_role("textbox", name="Deliver To", exact=True).click()
    page.get_by_role("textbox", name="Deliver To", exact=True).fill("SP D0.136")
    page.get_by_role("textbox", name="Deliver To", exact=True).press("Enter")
    page.get_by_role("button", name="Accounting collapsed").click()
    page.get_by_role("combobox", name="Account Assignment K (Cost").click()
    page.get_by_role("link", name="P (Project)").click()
    page.get_by_role("combobox", name="Project/WBS (no value) Error").click()
    page.get_by_role("link", name="Browse all").click()
    page.get_by_role("textbox", name="Type search term here").click()
    page.get_by_role("textbox", name="Type search term here").fill("C.2329.0320")
    page.get_by_role("textbox", name="Type search term here").press("Enter")
    page.get_by_role("button", name="Search", exact=True).click()
    page.get_by_role("button", name="choose Project/WBS C.2329.0320", exact=True).click()
    page.get_by_role("combobox", name="ShipTo(Plant) (no value)").click()
    page.get_by_role("link", name="0006 (UvA - Centraal Magazijn").click()
    page.get_by_label("Item 2: test2d").get_by_role("button", name="Toggle item details").click()
    page.get_by_label("Item 2: test2d").get_by_role("button", name="Accounting collapsed").click()
    page.get_by_role("combobox", name="Account Assignment K (Cost").click()
    page.get_by_role("link", name="P (Project)").click()
    page.get_by_role("combobox", name="Project/WBS (no value) Error").click()
    page.get_by_role("link", name="Browse all").click()
    page.get_by_role("textbox", name="Type search term here").click()
    page.get_by_role("textbox", name="Type search term here").fill("C.2329.0320")
    page.get_by_role("button", name="Search", exact=True).click()
    page.get_by_role("button", name="choose Project/WBS C.2329.0320", exact=True).click()
    page.get_by_role("combobox", name="ShipTo(Plant) (no value)").click()
    page.get_by_role("link", name="0006 (UvA - Centraal Magazijn").click()
    page.get_by_label("Item 3: test3d").get_by_role("button", name="Toggle item details").click()
    page.get_by_label("Item 3: test3d").get_by_role("button", name="Accounting collapsed").click()
    page.get_by_role("combobox", name="Account Assignment K (Cost").click()
    page.get_by_role("link", name="P (Project)").click()
    page.get_by_role("combobox", name="Project/WBS (no value) Error").click()
    page.get_by_role("link", name="Browse all").click()
    page.get_by_role("textbox", name="Type search term here").click()
    page.get_by_role("textbox", name="Type search term here").fill("C.2329.0320")
    page.get_by_role("button", name="Search", exact=True).click()
    page.get_by_role("button", name="choose Project/WBS C.2329.0320", exact=True).click()
    page.get_by_role("combobox", name="ShipTo(Plant) (no value)").click()
    page.get_by_role("link", name="0006 (UvA - Centraal Magazijn").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
